import type { Metadata } from "next";
import Link from 'next/link';

import {AddPage} from "./components/Home/Home"
import {Mentors} from "./components/Mentors/Mentors"
import {In_numbers} from "./components/In_numbers/In_numbers"
import {Vip} from "./components/Vip/Vip"
import {Card} from "./components/Card/Card"
import Faq from "./components/Faq/faq"
import styles from "./css/page.module.css";

export const metadata: Metadata = {
  title: "Art",
  description: "Generated by create next app",
  icons: {
    icon: "../favicon.ico",
  },
};

export default function Home() {
  return (
    <div className={styles.page}>
      <AddPage/>
      <Mentors/>
      <Card/>
      <Vip/>
      <In_numbers/>
      <Faq/>
    </div>
  );
}
